---
title: mekuate.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: giselemekuate@gmail.com
description: Sharing my digital Journey in Information Management especially data
  management, Website Development and online Community Management.
baseurl: ''
url: http://www.mekuate.com
host: 127.0.0.1
port: '4000'
permalink: "/:title"
twitter: gmekuate
github: mekuate
linkedin: mekuate
facebook: giselemekuate
avatar: profile.jpg
author: Gisele Mekuate-Defo
google_analytics: UA-91028607-1
tel: "+237 674 00 18 42"
country: Cameroun
City: Yaounde
resume: resume.pdf
profile_summary: Gisele Mekuate-Defo is the founder of mekuate web&app. she hold a
  master degree in Information Technmoly and Business Management. Founder of Mekuate
  web&App, she loves digital project and opportunity to learn new technology
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- octopress-autoprefixer
- jekyll-admin
- algoliasearch-jekyll
algolia:
  application_id: K39R7UJ94T
  index_name: jekyllPROD
  read_only_api_key: 97485f8cf12b038a6c81c0f25dfa7de0
  excluded_files:
  - 404.html
  - index.html
exclude:
- Gemfile
- Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
